name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Postman Newman
      - name: Install Newman
        run: npm install -g newman

      # Install correct Chrome version manually
      - name: Install Chrome (latest stable)
        run: |
          sudo apt update
          sudo apt install -y wget curl unzip
          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb || sudo apt -f install -y
          rm google-chrome.deb

      # Install compatible ChromeDriver
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          echo "Detected Chrome major version: $CHROME_VERSION"
          wget -q -O chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROME_VERSION}.0.6998.35/chromedriver_linux64.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver.zip
          chmod +x /usr/local/bin/chromedriver

      # Install Selenium
      - name: Install Selenium
        run: pip install selenium

      # Run UI Tests
      - name: Run UI Tests
        run: python test_script.py
