name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api_tests:
     name: API Testing
     runs-on: ubuntu-latest

     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Install Newman
         run: npm install -g newman

       - name: Run API Tests
         run: newman run APITesting.postman_collection.json

  ui_tests:
    name: UI Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install selenium webdriver-manager

      - name: Run UI Tests
        run: python test_script.py
